name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when pushing to main branch
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: github-pages  # ✅ Ensures artifact name is correct
          path: .  # ✅ Ensure this points to your static files

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
