name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: self-hosted  # Runs on local self-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-artifact@v4  # Correct version for GitHub Pages
        with:
          path: .  # Upload all files in the repo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
